version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: barber
      POSTGRES_USER: barber
      POSTGRES_DB: barber
    ports:
      - '5432:5432'
